### PR TITLE
Add newline at end of bash script output

### PR DESCRIPTION
**Pull request by soulofmischief**
Creates nicer output. :)

### CODE REVIEW

**Comment by aspacca** [comment]
thanks @soulofmischief 
but indeed the absence of newline in transer.sh output is a intended behaviour since the beginning in order to be clipboard friendly, and I never felt to change it

I would rather add an extra card with an example about out to print the `curl` output with an extra newline appended (here an example with a bash loop: https://github.com/dutchcoders/transfer.sh/issues/342)

what do you think?

**Comment by soulofmischief** [comment]
The issue I found was the absence of a newline made it harder to double-click and select the text since the prompt was next to it. I had to manually do a rectangle select.

In my experiment with adding the newline, I was still able to double-click and copy the URL with ease. I see an issue more with piping, which I can understand.

Maybe a flag in the function which optionally adds a newline? `transfer -n <file>` or something.

**Comment by aspacca** [comment]
> Maybe a flag in the function which optionally adds a newline? transfer -n <file> or something.

I favor this solution. If you are fine you can implement it (with usage description in the example card)

**Comment by saivishnu725** [comment]
The reason this pr was not merged makes sense but 
image this doesn't look nice at all.

**Comment by aspacca** [comment]
@saivishnu725

trailing newline should be achieved in the shell, not directly in the transfer.sh output.
here's one of the multiple way to achieve it
```
echo "$(curl -s --upload-file hello.txt https://transfer.sh/hello.txt)"
```

I'm open anyway to change `transfer()` shell function to accept `-n` param in order to add the trailing newline.
feel free to open a PR for it :)

**Comment by soulofmischief** [comment]
@aspacca would you prefer a compact one-off solution for catching `-n`, or do you think we should futureproof for more flags with `getopts`?

**Comment by aspacca** [comment]
@soulofmischief probably going to care for more future flags is too much of a concern, but I'd use some standard/well supported solution for params like `getops`anyway.
not much an expert on bash current standard for such kind of feature, but I'd go for it, whatever it is :)

what do you think?

**Comment by soulofmischief** [comment]
sounds good to me, I'll write it up this weekend.

**Comment by jtagcat** [comment]
Please use `printf` instead of `echo`. `echo` does not interpret newlines like that.

**Pull request closed without merging**
