### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by guanzi008**
中文汉化

### CODE REVIEW

**Comment by aspacca** [comment]
hello @guanzi008 , thanks for opening the PR
anyway your changes will replace the version in English with the Chinese one.
I guess what we sould aim for is to add multi languages support.

I have to think how to implement this. @stefanbenten, any hint?

**Comment by guanzi008** [comment]
http://144.34.209.19:8080/
多语言应该可以实现，有时间研究一下看看。

**Comment by stefanbenten** [comment]
My first guess would be a language table in the respective languages and then having a runtime flag to chose from it. Problematic might be the building and including of all assets.

Lemme play around with my previous attempts/changes and see what can be done.

**Comment by guanzi008** [comment]
期待(๑˙ー˙๑)。

**Comment by aspacca** [comment]
> My first guess would be a language table in the respective languages and then having a runtime flag to chose from it.

doing this on frontend side, is it?
there's probably some standard solution for localising in the grunt/bower ecosystem we shoud look for


>Problematic might be the building and including of all assets

we could have assets localized in a language folder, and just build the url with that.
but again, let's look for standard localization solution given the tools we use

**Comment by stefanbenten** [comment]
Sounds like a solid route. I was looking into the go way of handling it using the `go-i18n` package.
Do not have strong preference for either route.

**Pull request closed without merging**
